services:
    app:
      container_name: edu_meet_bot_dev
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      command: >
        bash -c "
          echo '>>> Postgres is up! Running Alembic migrations...';
          alembic upgrade head;
          echo '>>> Starting Bot...';
          poetry run start
        "
      volumes:
        - ./edu_meet_bot:/app/edu_meet_bot
      restart: always
      env_file:
        - .env

    db:
      container_name: edu_meet_bot_db_dev
      image: postgres:latest
      environment:
        - POSTGRES_DB=${POSTGRES_DB_NAME}
        - POSTGRES_USER=${POSTGRES_DB_USER}
        - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      ports:
        - ${POSTGRES_DB_HOST_PORT}:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]
        interval: 10s
        timeout: 5s
        retries: 5

      volumes:
        - ./db_data:/var/lib/postgresql/data
      restart: always
