"""empty message

Revision ID: 3b952734569c
Revises: 2bb38ee2987c
Create Date: 2024-11-16 16:19:59.387838+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b952734569c'
down_revision: Union[str, None] = '2bb38ee2987c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['last_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
