"""empty message

Revision ID: 0ed8d5ec4da0
Revises: 12c6d825e336
Create Date: 2024-11-05 14:00:47.708086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed8d5ec4da0'
down_revision: Union[str, None] = '12c6d825e336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_subject', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('academic_subject', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user', 'timezone',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timezone',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user', 'updated_at')
    op.drop_column('academic_subject', 'updated_at')
    op.drop_column('academic_subject', 'created_at')
    # ### end Alembic commands ###
