"""empty message

Revision ID: 2bb38ee2987c
Revises: ac9c3f7ee59f
Create Date: 2024-11-16 16:16:20.680685+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bb38ee2987c'
down_revision: Union[str, None] = 'ac9c3f7ee59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('slot', sa.Column('time_start', sa.Time(), nullable=False))
    op.add_column('slot', sa.Column('time_end', sa.Time(), nullable=False))
    op.add_column('slot', sa.Column('tutor_id', sa.Integer(), nullable=False))
    op.add_column('slot', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('slot', sa.Column('comment', sa.String(), nullable=True))
    op.create_foreign_key(None, 'slot', 'user', ['student_id'], ['id'])
    op.create_foreign_key(None, 'slot', 'user', ['tutor_id'], ['id'])
    op.drop_column('slot', 'duration')
    op.drop_column('slot', 'day_of_week')
    op.drop_column('slot', 'is_recurring')
    op.drop_column('slot', 'hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('hour', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('slot', sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('slot', sa.Column('day_of_week', postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='day_of_week_enum'), autoincrement=False, nullable=False))
    op.add_column('slot', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_column('slot', 'comment')
    op.drop_column('slot', 'student_id')
    op.drop_column('slot', 'tutor_id')
    op.drop_column('slot', 'time_end')
    op.drop_column('slot', 'time_start')
    op.drop_column('slot', 'date')
    # ### end Alembic commands ###
