"""empty message

Revision ID: 5e54cbbd1ab4
Revises: 7fc4e09a118f
Create Date: 2024-12-02 12:27:29.343783+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e54cbbd1ab4'
down_revision: Union[str, None] = '7fc4e09a118f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
