"""empty message

Revision ID: aaebad612e58
Revises: 0d00328b9e03
Create Date: 2024-12-02 13:07:12.225840+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaebad612e58'
down_revision: Union[str, None] = '0d00328b9e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', 'canceled', name='order_status_enum'),
               type_=sa.Enum('pending', 'accepted', 'declined', 'canceled', name='order_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('slot', 'status',
               existing_type=postgresql.ENUM('available', 'pending', 'accepted', name='slot_status_enum'),
               type_=sa.Enum('available', 'pending', 'accepted', name='slot_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot', 'status',
               existing_type=sa.Enum('available', 'pending', 'accepted', name='slot_status_enum', native_enum=False),
               type_=postgresql.ENUM('available', 'pending', 'accepted', name='slot_status_enum'),
               existing_nullable=False)
    op.alter_column('order', 'status',
               existing_type=sa.Enum('pending', 'accepted', 'declined', 'canceled', name='order_status_enum', native_enum=False),
               type_=postgresql.ENUM('pending', 'accepted', 'declined', 'canceled', name='order_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
