"""Fix Slot model

Revision ID: af636e942cdb
Revises: c5d477f6c61b
Create Date: 2024-11-04 20:15:40.762494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af636e942cdb'
down_revision: Union[str, None] = 'c5d477f6c61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('duration', sa.Integer(), nullable=False))
    op.drop_column('slot', 'slot_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('slot_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('slot', 'duration')
    # ### end Alembic commands ###
